// Code generated by MockGen. DO NOT EDIT.
// Source: ./helm_loaders.go

// Package mock_helminstall is a generated GoMock package.
package mock_helminstall

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	helminstall "github.com/solo-io/go-utils/installutils/helminstall"
	action "helm.sh/helm/v3/pkg/action"
	chart "helm.sh/helm/v3/pkg/chart"
	cli "helm.sh/helm/v3/pkg/cli"
	release "helm.sh/helm/v3/pkg/release"
)

// MockActionConfigLoader is a mock of ActionConfigLoader interface
type MockActionConfigLoader struct {
	ctrl     *gomock.Controller
	recorder *MockActionConfigLoaderMockRecorder
}

// MockActionConfigLoaderMockRecorder is the mock recorder for MockActionConfigLoader
type MockActionConfigLoaderMockRecorder struct {
	mock *MockActionConfigLoader
}

// NewMockActionConfigLoader creates a new mock instance
func NewMockActionConfigLoader(ctrl *gomock.Controller) *MockActionConfigLoader {
	mock := &MockActionConfigLoader{ctrl: ctrl}
	mock.recorder = &MockActionConfigLoaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockActionConfigLoader) EXPECT() *MockActionConfigLoaderMockRecorder {
	return m.recorder
}

// NewActionConfig mocks base method
func (m *MockActionConfigLoader) NewActionConfig(namespace string) (*action.Configuration, *cli.EnvSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewActionConfig", namespace)
	ret0, _ := ret[0].(*action.Configuration)
	ret1, _ := ret[1].(*cli.EnvSettings)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// NewActionConfig indicates an expected call of NewActionConfig
func (mr *MockActionConfigLoaderMockRecorder) NewActionConfig(namespace interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewActionConfig", reflect.TypeOf((*MockActionConfigLoader)(nil).NewActionConfig), namespace)
}

// MockActionListLoader is a mock of ActionListLoader interface
type MockActionListLoader struct {
	ctrl     *gomock.Controller
	recorder *MockActionListLoaderMockRecorder
}

// MockActionListLoaderMockRecorder is the mock recorder for MockActionListLoader
type MockActionListLoaderMockRecorder struct {
	mock *MockActionListLoader
}

// NewMockActionListLoader creates a new mock instance
func NewMockActionListLoader(ctrl *gomock.Controller) *MockActionListLoader {
	mock := &MockActionListLoader{ctrl: ctrl}
	mock.recorder = &MockActionListLoaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockActionListLoader) EXPECT() *MockActionListLoaderMockRecorder {
	return m.recorder
}

// ReleaseList mocks base method
func (m *MockActionListLoader) ReleaseList(helmActionConfigLoader helminstall.ActionConfigLoader, namespace string) (helminstall.ReleaseListRunner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseList", helmActionConfigLoader, namespace)
	ret0, _ := ret[0].(helminstall.ReleaseListRunner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReleaseList indicates an expected call of ReleaseList
func (mr *MockActionListLoaderMockRecorder) ReleaseList(helmActionConfigLoader, namespace interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseList", reflect.TypeOf((*MockActionListLoader)(nil).ReleaseList), helmActionConfigLoader, namespace)
}

// MockReleaseListRunner is a mock of ReleaseListRunner interface
type MockReleaseListRunner struct {
	ctrl     *gomock.Controller
	recorder *MockReleaseListRunnerMockRecorder
}

// MockReleaseListRunnerMockRecorder is the mock recorder for MockReleaseListRunner
type MockReleaseListRunnerMockRecorder struct {
	mock *MockReleaseListRunner
}

// NewMockReleaseListRunner creates a new mock instance
func NewMockReleaseListRunner(ctrl *gomock.Controller) *MockReleaseListRunner {
	mock := &MockReleaseListRunner{ctrl: ctrl}
	mock.recorder = &MockReleaseListRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockReleaseListRunner) EXPECT() *MockReleaseListRunnerMockRecorder {
	return m.recorder
}

// Run mocks base method
func (m *MockReleaseListRunner) Run() ([]*release.Release, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run")
	ret0, _ := ret[0].([]*release.Release)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Run indicates an expected call of Run
func (mr *MockReleaseListRunnerMockRecorder) Run() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockReleaseListRunner)(nil).Run))
}

// SetFilter mocks base method
func (m *MockReleaseListRunner) SetFilter(filter string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetFilter", filter)
}

// SetFilter indicates an expected call of SetFilter
func (mr *MockReleaseListRunnerMockRecorder) SetFilter(filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetFilter", reflect.TypeOf((*MockReleaseListRunner)(nil).SetFilter), filter)
}

// MockChartLoader is a mock of ChartLoader interface
type MockChartLoader struct {
	ctrl     *gomock.Controller
	recorder *MockChartLoaderMockRecorder
}

// MockChartLoaderMockRecorder is the mock recorder for MockChartLoader
type MockChartLoaderMockRecorder struct {
	mock *MockChartLoader
}

// NewMockChartLoader creates a new mock instance
func NewMockChartLoader(ctrl *gomock.Controller) *MockChartLoader {
	mock := &MockChartLoader{ctrl: ctrl}
	mock.recorder = &MockChartLoaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockChartLoader) EXPECT() *MockChartLoaderMockRecorder {
	return m.recorder
}

// Load mocks base method
func (m *MockChartLoader) Load(name string) (*chart.Chart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", name)
	ret0, _ := ret[0].(*chart.Chart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load
func (mr *MockChartLoaderMockRecorder) Load(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockChartLoader)(nil).Load), name)
}
