// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/solo-io/go-utils/githubutils (interfaces: RepoClient)

// Package changelogutils_test is a generated GoMock package.
package changelogutils_test

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	github "github.com/google/go-github/github"
	githubutils "github.com/solo-io/go-utils/githubutils"
	reflect "reflect"
)

// MockRepoClient is a mock of RepoClient interface
type MockRepoClient struct {
	ctrl     *gomock.Controller
	recorder *MockRepoClientMockRecorder
}

// MockRepoClientMockRecorder is the mock recorder for MockRepoClient
type MockRepoClientMockRecorder struct {
	mock *MockRepoClient
}

// NewMockRepoClient creates a new mock instance
func NewMockRepoClient(ctrl *gomock.Controller) *MockRepoClient {
	mock := &MockRepoClient{ctrl: ctrl}
	mock.recorder = &MockRepoClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRepoClient) EXPECT() *MockRepoClientMockRecorder {
	return m.recorder
}

// CompareCommits mocks base method
func (m *MockRepoClient) CompareCommits(arg0 context.Context, arg1, arg2 string) (*github.CommitsComparison, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompareCommits", arg0, arg1, arg2)
	ret0, _ := ret[0].(*github.CommitsComparison)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CompareCommits indicates an expected call of CompareCommits
func (mr *MockRepoClientMockRecorder) CompareCommits(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompareCommits", reflect.TypeOf((*MockRepoClient)(nil).CompareCommits), arg0, arg1, arg2)
}

// CreateBranch mocks base method
func (m *MockRepoClient) CreateBranch(arg0 context.Context, arg1 string) (*github.Reference, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBranch", arg0, arg1)
	ret0, _ := ret[0].(*github.Reference)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBranch indicates an expected call of CreateBranch
func (mr *MockRepoClientMockRecorder) CreateBranch(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBranch", reflect.TypeOf((*MockRepoClient)(nil).CreateBranch), arg0, arg1)
}

// CreatePR mocks base method
func (m *MockRepoClient) CreatePR(arg0 context.Context, arg1 string, arg2 githubutils.PRSpec) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePR", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePR indicates an expected call of CreatePR
func (mr *MockRepoClientMockRecorder) CreatePR(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePR", reflect.TypeOf((*MockRepoClient)(nil).CreatePR), arg0, arg1, arg2)
}

// DirectoryExists mocks base method
func (m *MockRepoClient) DirectoryExists(arg0 context.Context, arg1, arg2 string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DirectoryExists", arg0, arg1, arg2)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DirectoryExists indicates an expected call of DirectoryExists
func (mr *MockRepoClientMockRecorder) DirectoryExists(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DirectoryExists", reflect.TypeOf((*MockRepoClient)(nil).DirectoryExists), arg0, arg1, arg2)
}

// FindLatestReleaseTagIncudingPrerelease mocks base method
func (m *MockRepoClient) FindLatestReleaseTagIncudingPrerelease(arg0 context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindLatestReleaseTagIncudingPrerelease", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindLatestReleaseTagIncudingPrerelease indicates an expected call of FindLatestReleaseTagIncudingPrerelease
func (mr *MockRepoClientMockRecorder) FindLatestReleaseTagIncudingPrerelease(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindLatestReleaseTagIncudingPrerelease", reflect.TypeOf((*MockRepoClient)(nil).FindLatestReleaseTagIncudingPrerelease), arg0)
}
